In [2]:
import pandas as pd

df= pd.read_csv("../data/credit_card_fraud.csv")

In [3]:
df.head()

,transaction_id,amount_usd,merchant_category,card_type,auth_method,channel,device_type,is_foreign_transaction,hours_since_last_txn,txn_count_last_24h,...,ip_country_mismatch,billing_shipping_mismatch,cvv_retry_count,velocity_score,time_of_day_hour,day_of_week,is_ai_generated_scam_attempt,merchant_risk_score,prior_disputes,is_fraud
0,1,42.86,Restaurants,Visa,OTP,Online,Android Phone,False,13.54,2,...,False,False,0,0.1,18,3,False,42.3,0,0
1,2,4.75,Online Retail,Mastercard,3D Secure,Online,Android Phone,False,0.71,2,...,False,False,0,25.8,12,4,False,28.3,0,0
2,3,77.18,Groceries,Mastercard,3D Secure,Online,Mac,False,0.35,5,...,False,True,0,42.3,5,0,False,24.7,1,0
3,4,1.69,Streaming,Visa,No Authentication,POS,Android Phone,False,3.42,6,...,False,False,0,28.9,22,6,False,56.2,1,0
4,5,261.68,Travel,Visa,3D Secure,In-App,iPhone,False,2.43,2,...,False,False,0,3.9,2,4,False,32.7,0,0

In [4]:
df.shape

(20000, 26)

In [5]:
df.size

520000

In [6]:
df.columns

Index(['transaction_id', 'amount_usd', 'merchant_category', 'card_type',
       'auth_method', 'channel', 'device_type', 'is_foreign_transaction',
       'hours_since_last_txn', 'txn_count_last_24h', 'distance_from_home_km',
       'card_age_months', 'customer_age', 'account_balance_usd',
       'is_new_merchant', 'used_vpn', 'ip_country_mismatch',
       'billing_shipping_mismatch', 'cvv_retry_count', 'velocity_score',
       'time_of_day_hour', 'day_of_week', 'is_ai_generated_scam_attempt',
       'merchant_risk_score', 'prior_disputes', 'is_fraud'],
      dtype='str')

In [7]:
df.dtypes

transaction_id                    int64
amount_usd                      float64
merchant_category                   str
card_type                           str
auth_method                         str
channel                             str
device_type                         str
is_foreign_transaction             bool
hours_since_last_txn            float64
txn_count_last_24h                int64
distance_from_home_km           float64
card_age_months                   int64
customer_age                      int64
account_balance_usd             float64
is_new_merchant                    bool
used_vpn                           bool
ip_country_mismatch                bool
billing_shipping_mismatch          bool
cvv_retry_count                   int64
velocity_score                  float64
time_of_day_hour                  int64
day_of_week                       int64
is_ai_generated_scam_attempt       bool
merchant_risk_score             float64
prior_disputes                    int64
is_fraud                          int64
dtype: object

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 26 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   transaction_id                20000 non-null  int64
 1   amount_usd                    20000 non-null  float64
 2   merchant_category             20000 non-null  str
 3   card_type                     20000 non-null  str
 4   auth_method                   20000 non-null  str
 5   channel                       20000 non-null  str
 6   device_type                   20000 non-null  str
 7   is_foreign_transaction        20000 non-null  bool
 8   hours_since_last_txn          20000 non-null  float64
 9   txn_count_last_24h            20000 non-null  int64
 10  distance_from_home_km         20000 non-null  float64
 11  card_age_months               20000 non-null  int64
 12  customer_age                  20000 non-null  int64
 13  account_balance_usd           20000 non-null  float64
 14  is_new_merchant               20000 non-null  bool
 15  used_vpn                      20000 non-null  bool
 16  ip_country_mismatch           20000 non-null  bool
 17  billing_shipping_mismatch     20000 non-null  bool
 18  cvv_retry_count               20000 non-null  int64
 19  velocity_score                20000 non-null  float64
 20  time_of_day_hour              20000 non-null  int64
 21  day_of_week                   20000 non-null  int64
 22  is_ai_generated_scam_attempt  20000 non-null  bool
 23  merchant_risk_score           20000 non-null  float64
 24  prior_disputes                20000 non-null  int64
 25  is_fraud                      20000 non-null  int64
dtypes: bool(6), float64(6), int64(9), str(5)
memory usage: 3.9 MB

In [9]:
df.isnull().sum()

transaction_id                  0
amount_usd                      0
merchant_category               0
card_type                       0
auth_method                     0
channel                         0
device_type                     0
is_foreign_transaction          0
hours_since_last_txn            0
txn_count_last_24h              0
distance_from_home_km           0
card_age_months                 0
customer_age                    0
account_balance_usd             0
is_new_merchant                 0
used_vpn                        0
ip_country_mismatch             0
billing_shipping_mismatch       0
cvv_retry_count                 0
velocity_score                  0
time_of_day_hour                0
day_of_week                     0
is_ai_generated_scam_attempt    0
merchant_risk_score             0
prior_disputes                  0
is_fraud                        0
dtype: int64

In [10]:
df.nunique()

transaction_id                  20000
amount_usd                      12782
merchant_category                  12
card_type                           5
auth_method                         5
channel                             5
device_type                         8
is_foreign_transaction              2
hours_since_last_txn             3296
txn_count_last_24h                 13
distance_from_home_km            6121
card_age_months                    52
customer_age                       64
account_balance_usd             19629
is_new_merchant                     2
used_vpn                            2
ip_country_mismatch                 2
billing_shipping_mismatch           2
cvv_retry_count                     4
velocity_score                    634
time_of_day_hour                   24
day_of_week                         7
is_ai_generated_scam_attempt        2
merchant_risk_score               940
prior_disputes                      5
is_fraud                            2
dtype: int64

In [11]:
df[df.duplicated()]

Empty DataFrame
Columns: [transaction_id, amount_usd, merchant_category, card_type, auth_method, channel, device_type, is_foreign_transaction, hours_since_last_txn, txn_count_last_24h, distance_from_home_km, card_age_months, customer_age, account_balance_usd, is_new_merchant, used_vpn, ip_country_mismatch, billing_shipping_mismatch, cvv_retry_count, velocity_score, time_of_day_hour, day_of_week, is_ai_generated_scam_attempt, merchant_risk_score, prior_disputes, is_fraud]
Index: []

[0 rows x 26 columns]

In [12]:
df["is_fraud"].value_counts(normalize=True)*100

is_fraud
0    98.305
1     1.695
Name: proportion, dtype: float64

In [13]:
df["merchant_category"].unique()

<ArrowStringArray>
[    'Restaurants',   'Online Retail',       'Groceries',       'Streaming',
          'Travel',      'Gift Cards',     'Electronics',            'Fuel',
          'Gaming',       'Utilities', 'Crypto Exchange',      'Healthcare']
Length: 12, dtype: str